### ISSUE TITLE
dbconn.php missing !!!

### ISSUE THREAD

**Issue by chetanRegmi** [andrewlouie/ToyCharm#1]

**Comment by chetanRegmi** [comment]
Static analysis:

3 errors were found during analysis.

Unrecognized data type. (near "BOOL" at position 252)
Unrecognized data type. (near "BOOL" at position 393)
Unrecognized data type. (near "BOOL" at position 425)
SQL query:

CREATE TABLE mysql.toys ( item INT(11) UNSIGNED NOT NULL AUTO_INCREMENT, title VARCHAR(255) NOT NULL, shortdesc VARCHAR(255) DEFAULT NULL, date DATE DEFAULT NULL, price DOUBLE(10, 3) DEFAULT NULL, pics VARCHAR(255) DEFAULT NULL, featured BOOL DEFAULT NULL, longdesc VARCHAR(1000) DEFAULT NULL, quantity INT(11) DEFAULT NULL, saleprice DOUBLE(10, 3) DEFAULT NULL, visible BOOL DEFAULT NULL, bestseller BOOL DEFAULT NULL, cat_id INT(5) DEFAULT NULL, PRIMARY KEY (item) ) ENGINE = MYISAM AUTO_INCREMENT = 1 CHARACTER SET latin1 COLLATE latin1_swedish_ci

MySQL said: Documentation

#1050 - Table 'toys' already exists

**Comment by andrewlouie** [comment]
Hi chetanRegmi,

DBConn is missing because it has a password in it but it just sets the variables, looks like this:
<?php
$username = "username";
$password = "password";
$host = "mysqlserver.com";
$dbname = "dbname";
?>

As for the error you're getting about datatype BOOL, you many need to change that to TINYINT.  Some MySQL server's I've found don't have a BOOL datatype and just use 0 or 1 instead so if that's the case there may be some other changes to the PHP for inserting items as well.

Hope this helps.

Andrew
